### ISSUE TITLE
Confusion with callback click and double click

### ISSUE THREAD

**Issue by Nosfistis** [jsware/able-buttons#5]
**Is your feature request related to a problem? Please describe.**
The clicked/double-clicked feature is a bit difficult to handle, as each double click also counts as 2 click events.

**Describe the solution you'd like**
I would like to separate actions between click and double-click using callback mode.

**Describe alternatives you've considered**
At the moment I am implementing a debounce mechanic of my own to check whether a click is actually part of a double click.

**Comment by JohnScottUK** [comment]
Fixed in V0.4.0
